### ISSUE TITLE
GEMM MK_NK_MN incorrect results

### ISSUE THREAD

**Issue by j4yan** [ROCm/composable_kernel#225] opened 2022-05-05 15:01 UTC
on develop 3956085d8eb913ad4c5

./bin/ckProfiler gemm 0 1 1 2 0 0 256 256 4097 -1 -1 -1
./bin/ckProfiler gemm 1 1 1 2 0 0 256 256 4097 -1 -1 -1

generates 

        out[0] != ref[0]: 2.691406 != 2.453125
Error: Incorrect results!
        out[1] != ref[1]: -9.367188 != -9.28125
Error: Incorrect results!
        out[2] != ref[2]: -0.4934082 != -0.456543
Error: Incorrect results!
        out[3] != ref[3]: -12.83594 != -13.13281
Error: Incorrect results!
   max err: 0.5

**Comment by asroy** [comment] 2022-05-05 17:45
the root cause is in IsSupportedArgument() and CheckValidity()

**Comment by ppanchad-amd** [comment] 2024-08-20 17:51
@j4yan Please advise if we can close this ticket as fixed. Thanks!

**Comment by ppanchad-amd** [comment] 2024-09-25 19:34
@j4yan Closing ticket. Please feel free to re-open the ticket if you still see the issue with the latest ROCm and we will further investigate the issue. Thanks!

**Closed by ppanchad-amd** 2024-09-25 19:34 UTC
Labels: bug
