### ISSUE TITLE
Severe FP16 conv precision and perf regression on gfx90a

### ISSUE THREAD

**Issue by atafra** [ROCm/composable_kernel#671] opened 2023-04-09 15:40 UTC
PR #603 has significantly degraded FP16 convolution precision on `gfx90a`, which makes the kernel unusable for our workload. Performance also got worse by close to 2x. It seems that internally BF16 MMA is used instead of FP16 to work around some denorm issue. Using a different data type with fewer mantissa bits than the original is not an acceptable general workaround. FP16 is typically used on purpose because BF16 does not have enough precision for the respective workload.

What's this denorm issue that this workaround tries to solve?

Regardless, could you please add a macro / build option to enable/disable this workaround? Some workloads like ours is do not seem to be affected by the denorm issue but require that the specified data type is actually used. I don't think that this workaround is robust enough that it should be permanently enabled.

**Comment by zjing14** [comment] 2023-04-10 15:37
@atafra Yes, we are working on adding a switch to turn on/off the denorm fix.

**Comment by atafra** [comment] 2023-04-10 15:43
Thanks! What exactly is this denorm issue?

**Comment by zjing14** [comment] 2023-04-10 15:57
I am not sure what the problem is exactly. Let me check.

**Comment by zjing14** [comment] 2023-04-10 16:48
PR https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/673

**Comment by zjing14** [comment] 2023-04-11 12:45
PR Merged

**Closed as completed by zjing14** 2023-04-11 12:45 UTC
