### ISSUE TITLE
Compilation failure with the custom data type

### ISSUE THREAD

**Issue by zjing14** [ROCm/composable_kernel#1656] opened 2024-11-11 21:34 UTC
Got the compilation error with a custom data type
```
/home/jizhan/composable_kernel_pk_i4/include/ck/utility/dynamic_buffer.hpp:344:56: error: object of type 'ck::non_native_vector_base<ck::pk_i4_t, 16>' cannot be assigned because its copy assignment operator is implicitly deleted
  344 |                 *c_style_pointer_cast<X*>(&p_data_[i]) = x;
      |                                                        ^
```
Below is a simple reproduction.
```
    struct custom_f8_t
    {
        using type = _BitInt(8);
        type data;
        custom_f8_t() : data{type{}} {}
        custom_f8_t(type init) : data{init} {}
    };

    // test size
    const int size                   = 4;
    std::vector<_BitInt(8)> test_vec = {type_convert<_BitInt(8)>(0.3f),
                                        type_convert<_BitInt(8)>(-0.6f),
                                        type_convert<_BitInt(8)>(0.8f),
                                        type_convert<_BitInt(8)>(-0.2f)};
    // reference vector
    vector_type<custom_f8_t, size> right_vec;
    // check default CTOR
    ck::static_for<0, size, 1>{}(
        [&](auto i) { ASSERT_EQ(right_vec.template AsType<custom_f8_t>()(Number<i>{}).data, 0); });
    // assign test values to the vector
    ck::static_for<0, size, 1>{}([&](auto i) {
        right_vec.template AsType<custom_f8_t>()(Number<i>{}) = custom_f8_t{test_vec.at(i)};
    });

    //Compilation Error: cannot be assigned because its copy assignment operator is
    //implicitly deleted
    vector_type<custom_f8_t, size> left_vec;
    left_vec = right_vec;
```

**Comment by zjing14** [comment] 2024-11-11 22:34
@geyyer @carlushuang

**Comment by geyyer** [comment] 2024-11-12 15:44
Hi @zjing14, thanks for reporting this issue. The repro code you are using is a part of our test and is run daily. Could you share more details about your build setup so we can compare it to our CI?

**Comment by zjing14** [comment] 2024-11-12 18:37
@geyyer It is not an issue in the existing code. I am trying to add `pk_int4` as a custom data type rather `uint8_t`, which is already used for bfp8.

You can reproduce the issue with the modified test code as below.

```
struct custom_f8_t
    {
        using type = _BitInt(8);
        type data;
        custom_f8_t() : data{type{}} {}
        custom_f8_t(type init) : data{init} {}
    };

    // test size
    const int size                   = 4;
    std::vector<_BitInt(8)> test_vec = {type_convert<_BitInt(8)>(0.3f),
                                        type_convert<_BitInt(8)>(-0.6f),
                                        type_convert<_BitInt(8)>(0.8f),
                                        type_convert<_BitInt(8)>(-0.2f)};
    // reference vector
    vector_type<custom_f8_t, size> right_vec;
    // check default CTOR
    ck::static_for<0, size, 1>{}(
        [&](auto i) { ASSERT_EQ(right_vec.template AsType<custom_f8_t>()(Number<i>{}).data, 0); });
    // assign test values to the vector
    ck::static_for<0, size, 1>{}([&](auto i) {
        right_vec.template AsType<custom_f8_t>()(Number<i>{}) = custom_f8_t{test_vec.at(i)};
    });

    //Compilation Error: cannot be assigned because its copy assignment operator is
    //implicitly deleted
    vector_type<custom_f8_t, size> left_vec;
    left_vec = right_vec;
```

**Comment by geyyer** [comment] 2024-11-13 17:05
@zjing14, I see your point. Would a copy constructor like `vector_type<custom_f8_t, size> left_vec{right_vec};` work for you? Or would you like a copy assignment operator to be added?

**Comment by zjing14** [comment] 2024-11-14 02:43
@geyyer a copy assignment is needed otherwise we need to change a lot of places in `copy` and `dynamc_buffer`.

**Comment by geyyer** [comment] 2024-11-14 15:26
@zjing14, sure, we'll add it!

**Comment by mtgu0705** [comment] 2024-11-27 06:41
@geyyer, Could you please assist in expediting the progress of this issue?

**Comment by geyyer** [comment] 2024-12-02 20:51
@mtgu0705 sure, I will look into it!

**Comment by geyyer** [comment] 2024-12-05 00:29
@zjing14, @mtgu0705, the issue is already resolved by the PR https://github.com/ROCm/composable_kernel/pull/1710. Meanwhile, I’m adding tests to cover such cases in the future https://github.com/ROCm/composable_kernel/pull/1718.

**Closed as completed by geyyer** 2024-12-05 00:29 UTC
Labels: Under Investigation
