### ISSUE TITLE
Gemm produce incorrect result under certain input shape configuration

### ISSUE THREAD

**Issue by PeixuanZuo** [ROCm/composable_kernel#512] opened 2022-11-16 09:53 UTC
on develop 4c4c7328a6a0c593a445c8a5be79cf1586fe58d4

Gemm produce incorrect result under certain input shape configuration:
dtype=float16 TT m=128   n=1024  k=3
dtype=float16 TT m=1024  n=128   k=1
dtype=float16 NT m=128   n=1024  k=133
...

for example:

./bin/ckProfiler gemm 1 3 1 2 0 0 128 128 133 -1 -1 -1

it generate:
```
a_m_k: dim 2, lengths {128, 133}, strides {1, 128}
b_k_n: dim 2, lengths {133, 128}, strides {1, 133}
c_m_n: dim 2, lengths {128, 128}, strides {128, 1}
found 25 instances
DeviceGemmXdl<256, 256, 128, 4, 8, 32, 32, 4, 2> does not support this problem
DeviceGemmXdl<256, 128, 256, 4, 8, 32, 32, 2, 4> does not support this problem
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemmXdl<128, 128, 128, 4, 8, 32, 32, 4, 2>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemmXdl<256, 128, 128, 4, 8, 32, 32, 2, 2>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemmXdl<128, 128, 64, 4, 8, 32, 32, 2, 2>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemmXdl<128, 64, 128, 4, 8, 32, 32, 2, 2>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemmXdl<256, 128, 64, 4, 8, 32, 32, 2, 1>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemmXdl<256, 64, 128, 4, 8, 32, 32, 1, 2>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
DeviceGemmDl<256, 128, 128, 16, 2, 4, 4, 1> does not support this problem
DeviceGemm_Xdl_CShuffle<256, 256, 128, 32, 2, 8> does not support this problem
DeviceGemm_Xdl_CShuffle<256, 256, 128, 32, 8, 8> does not support this problem
DeviceGemm_Xdl_CShuffle<256, 128, 256, 32, 2, 8> does not support this problem
DeviceGemm_Xdl_CShuffle<256, 128, 256, 32, 8, 8> does not support this problem
DeviceGemm_Xdl_CShuffle<128, 128, 128, 32, 2, 8> does not support this problem
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemm_Xdl_CShuffle<128, 128, 128, 32, 8, 8>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
DeviceGemm_Xdl_CShuffle<256, 128, 128, 32, 2, 8> does not support this problem
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemm_Xdl_CShuffle<256, 128, 128, 32, 8, 8>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
DeviceGemm_Xdl_CShuffle<128, 128, 64, 32, 2, 8> does not support this problem
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemm_Xdl_CShuffle<128, 128, 64, 32, 8, 8>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
DeviceGemm_Xdl_CShuffle<128, 64, 128, 32, 2, 8> does not support this problem
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemm_Xdl_CShuffle<128, 64, 128, 32, 8, 8>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
DeviceGemm_Xdl_CShuffle<256, 128, 64, 32, 2, 8> does not support this problem
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemm_Xdl_CShuffle<256, 128, 64, 32, 8, 8>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
DeviceGemm_Xdl_CShuffle<256, 64, 128, 32, 2, 8> does not support this problem
Perf:          0 ms, inf TFlops, inf GB/s, DeviceGemm_Xdl_CShuffle<256, 64, 128, 32, 8, 8>
Error: Incorrect results!        out[0] != ref[0]: 1.024414 != 0.7519531
Error: Incorrect results!        out[1] != ref[1]: -0.4521484 != -0.21521
Error: Incorrect results!        out[2] != ref[2]: -3.208984 != -3.462891
Error: Incorrect results!        out[3] != ref[3]: 0.862793 != 0.1235962
   max err: 1.375244
Best Perf for datatype = f16 ALayout =  ColumnMajor BLayout =  ColumnMajor M = 128 N = 128 K = 133 StrideA = 128 StrideB = 133 StrideC = 128 : 0 ms, inf TFlops, inf GB/s, DeviceGemmXdl<128, 128, 128, 4, 8, 32, 32, 4, 2>
```

**Comment by rosenrodt** [comment] 2022-11-22 01:49
Those kernels producing the wrong results shouldn't be running in the first place. The problem size K is not divisible by kernel's tiling of K per block nor is it K-padded.

We currently only have prebuilt kernels supporting GEMM M/N/K that is divisible by kernel tiling size M/N/KPerBlock. From the log, seems like CK can correctly reject cases when problem size M/N is not divisible by M/NPerBlock, but failed to do so when K is not divisible by KPerBlock.

**Comment by PeixuanZuo** [comment] 2022-11-22 02:58
Thanks [rosenrodt](https://github.com/rosenrodt), will CK add rejection of unsupported k for Gemm? Or do we need to add judgment when using it?

**Comment by illsilin** [comment] 2022-11-22 23:13
I think we will improve the logic of the function that evaluates whether the problem size is supported or not. Since CK is still in a fairly early stage and we've been mostly focused on a limited set of benchmarks, we haven't had a chance to make our problem selection logic completely foolproof.

**Comment by PeixuanZuo** [comment] 2022-11-23 13:04
It would be great if it will be fixed, we consider using ck in the production, correctness is the first thing we want to ensure. Because of it produces incorrect result silently in some input configuration, it may brings potential mistakes. Hopefully ck will improve to judge whether specific cases support or not. Thanks.

**Comment by illsilin** [comment] 2022-11-23 16:53
Yes, we are working on making sure that CK meets the industrial quality standards. We have already implemented daily QA tests that check correctness and performance for more than a thousand kernels with various data types, data layouts, on different GPU architectures and with different compiler versions. And we'll continue to expand the test suite as new features are added or as new bugs are discovered.

**Comment by illsilin** [comment] 2022-11-23 22:16
OK, I've found the root cause of this issue. I think we'll need to discuss how to handle it with Chao and Jing when they return from vacation next week, but it should be fairly simple. We should be able to fix it next week.

**Comment by PeixuanZuo** [comment] 2022-11-28 03:42
Please let my know if you have any improvement, Thanks!

**Comment by illsilin** [comment] 2022-12-08 18:16
We've merged a fix that will make sure that all those odd tensor sizes without padding will end up throwing the "this problem size is not supported" message.

**Comment by zjing14** [comment] 2022-12-13 19:17
@PeixuanZuo Please verify the fix.

**Comment by PeixuanZuo** [comment] 2022-12-14 05:32
Thanks for your fix, I tested  commit d58b7f5155b44c8b608f3edc6a6eab314493ec1a on my test cases and they all passed.

**Comment by xiaobo1025** [comment] 2024-02-23 10:45
@PeixuanZuo Hello, I do not understand the division principles of these parameters, such as: 
typename ADataType,
    typename BDataType,
    typename CDataType,
    typename AccDataType,
    typename ALayout,
    typename BLayout,
    typename CLayout,
    typename AElementwiseOperation,
    typename BElementwiseOperation,
    typename CElementwiseOperation,
    GemmSpecialization GemmSpec,
    index_t BlockSize,
    index_t MPerBlock,
    index_t NPerBlock,
    index_t K0PerBlock,
    index_t K1,
    index_t M1PerThread,
    index_t N1PerThread,
    index_t KPerThread,
    typename M1N1ThreadClusterM1Xs,
    typename M1N1ThreadClusterN1Xs,
    typename ABlockTransferThreadSliceLengths_K0_M0_M1_K1,
    typename ABlockTransferThreadClusterLengths_K0_M0_M1_K1,
    typename ABlockTransferThreadClusterArrangeOrder,
    typename ABlockTransferSrcAccessOrder,
    typename ABlockTransferSrcVectorTensorLengths_K0_M0_M1_K1,
    typename ABlockTransferSrcVectorTensorContiguousDimOrder,
    typename ABlockTransferDstVectorTensorLengths_K0_M0_M1_K1,
    typename BBlockTransferThreadSliceLengths_K0_N0_N1_K1,
    typename BBlockTransferThreadClusterLengths_K0_N0_N1_K1,
    typename BBlockTransferThreadClusterArrangeOrder,
    typename BBlockTransferSrcAccessOrder,
    typename BBlockTransferSrcVectorTensorLengths_K0_N0_N1_K1,
    typename BBlockTransferSrcVectorTensorContiguousDimOrder,
    typename BBlockTransferDstVectorTensorLengths_K0_N0_N1_K1,
    typename CThreadTransferSrcDstAccessOrder,
    index_t CThreadTransferSrcDstVectorDim,
    index_t CThreadTransferDstScalarPerVector,
For a specific matrix multiplication, how should I determine the values of these parameters?Could you please give me some valuable advice? thank you very much!

**Comment by xiaobo1025** [comment] 2024-02-23 11:02
@PeixuanZuo Hello, have you solved all the problems you encountered before?

**Comment by PeixuanZuo** [comment] 2024-02-26 02:35
> @PeixuanZuo Hello, have you solved all the problems you encountered before?

@xiaobo1025 CK has been fixed this issue.

**Comment by xiaobo1025** [comment] 2024-02-26 03:35
@PeixuanZuoOh,thank you very much! Do you have any further understanding of these matrix dimensions and parameters?

**Comment by PeixuanZuo** [comment] 2024-02-26 04:08
> @PeixuanZuoOh,thank you very much! Do you have any further understanding of these matrix dimensions and parameters?

@xiaobo1025 I'm not familiar with these parameters, if you're just a user, you can refer to this [example](https://github.com/ROCm/composable_kernel/blob/develop/client_example/01_gemm/gemm.cpp) to find the fastest implementation for specific matrix multiplicatio, if you want to contribute to ck, please contact the developer of ck to give you more guidance.

**Comment by xiaobo1025** [comment] 2024-02-26 08:24
@PeixuanZuo Oh,thanks!Excuse me, how can I contact the developer of ck?

**Comment by PeixuanZuo** [comment] 2024-02-26 09:07
> @PeixuanZuo Oh,thanks!Excuse me, how can I contact the developer of ck?

@xiaobo1025 If you encounter issue, please create an issue to discribe your problem. If you have changes, please create a PR and add main contributor as reviewer. That might help you.

**Closed** 2024-02-26 09:10 UTC
